esphome:
  name: esp32-keypad
  friendly_name: eps32_keypad

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#   level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "aCKmnwd9IstYJeVKjkBAYg0rJWq653EkSUX9PO6ok1A="

ota:
  password: "2cccfa39563ab03314882de02676cf6a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bb-Keypad-V2 Fallback Hotspot"
    password: "ps14vKMS1yto"

captive_portal:

#connections: all buttons are on VIN and on their respective pins
#(we are relying on esp32s built-in pulldown resistors but could have used external resistors as well)
#Button 1: GPIO25 / 
#Button 2: GPIO26 / 
#Button 3: GPIO27 / 
#Button 4: GPIO14 / 

#Button 5: GPIO19 / 
#Button 6: GPIO18 / 
#Button 7: GPI17 / 
#Button 8: GPIO16 

binary_sensor:
  # Button 1
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 1"
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b1
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b1
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b1
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b1
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b1
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b1
            data:
              title: single_click
  #Button 2
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 2"
    pin:
      number: GPIO26
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b2
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b2
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b2
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b2
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b2
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b2
            data:
              title: single_click
  #Button 3
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 3"
    pin:
      number: GPIO27
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b3
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b3
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b3
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b3
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b3
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b3
            data:
              title: single_click
  #Button 4
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 4"
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b4
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b4
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b4
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b4
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b4
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b4
            data:
              title: single_click
    #Button 5
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 5"
    pin:
      number: GPIO19
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b5
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b5
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b5
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b5
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b5
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b5
            data:
              title: single_click
    #Button 6
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 6"
    pin:
      number: GPIO18
      mode:
        input: true
        pulldown: true
    id: esp32_keypad_b6
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b6
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b6
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b6
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b6
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b6
            data:
              title: single_click
    #Button 7
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 7"
    pin:
      number: GPIO17
      mode:
        input: true
        pulldown: true #was pulldown
    id: esp32_keypad_b7
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b7
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b7
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b7
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b7
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b7
            data:
              title: single_click
    #Button 8
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 8"
    pin:
      number: GPIO16
      mode:
        input: true
        pulldown: true
    id: esp32_keypad_b8
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b8
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b8
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b8
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b8
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_b8
            data:
              title: single_click