esphome:
  name: esp32-keypad
  friendly_name: eps32_keypad

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32 Keypad Fallback Hotspot"
    password: !secret ssid_password

captive_portal:

#connections: all buttons are on GND and on their respective pins
#(we are relying on esp32s built-in pullup resistors but could have used external resistors as well)
#Button 1: GPIO25 / 
#Button 2: GPIO26 / 
#Button 3: GPIO27 / 
#Button 4: GPIO14 / 

#Button 5: GPIO19 / 
#Button 6: GPIO18 / 
#Button 7: GPI17 / 
#Button 8: GPIO16 

binary_sensor:
  #Button 1
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 1"
    pin:
      number: GPIO25
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b1

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b1
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b1
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b1
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b1
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b1

  #Button 2
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 2"
    pin:
      number: GPIO26
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b2

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b2
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b2
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b2
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b2
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b2
  #Button 3
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 3"
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b3

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b3
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b3
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b3
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b3
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b3
  #Button 4
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 4"
    pin:
      number: GPIO14
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b4

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b4
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b4
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b4
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b4
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b4
  #Button 5
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 5"
    pin:
      number: GPIO19
      inverted: True
      mode: INPUT_PULLUP 
    id: esp32_keypad_b5

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b5
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b5
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b5
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b5
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b5
  #Button 6
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 6"
    pin:
      number: GPIO18
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b6

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b6
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b6
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b6
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b6
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b6
  #Button 7
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 7"
    pin:
      number: GPIO17
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b7

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b7
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b7
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b7
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b7
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b7
  #Button 8
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Keypad 2x4 Button 8"
    pin:
      number: GPIO16
      inverted: True
      mode: INPUT_PULLUP
    id: esp32_keypad_b8

    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Double Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: dbl_click
              button: b8
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log:
            format: "Triple Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: triple_click
              button: b8
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Long Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: long_click
              button: b8
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log:
            format: "Click and Hold"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: hold
              button: b8
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log:
            format: "Single Short Clicked"
            level: INFO
        - homeassistant.event:
            event: esphome.esp32_keypad_V2
            data:
              title: single_click
              button: b8
